reporter: mocha-multi
reporterOptions: 'spec=-,mocha-junit-reporter=-'
file: # Files that get loaded before suite execution.  Helpful when running a single file.
  - test/helpers/env.ts
  - test/helpers/hooks.ts
extension:
  - js
  - ts
require:
  - ts-node/register
  - tsconfig-paths/register
recursive: true
exit: true
