rules:
  # These overrides let us use anonymous functions for Mocha instead of lambdas, which is
  # the preferred method described in the Mocha docs
  prefer-arrow-callback: "off"
  func-names: "off"
  no-unused-expressions: "off" # Required for chai `to.be.empty`
  "@typescript-eslint/no-unused-expressions": ["off"]