apiVersion: apps/v1
kind: Deployment
metadata:
  name: harmony-work-scheduler
  labels:
    name: harmony-work-scheduler
spec:
  replicas: $SCHEDULER_POD_REPLICAS
  selector:
    matchLabels:
      name: harmony-work-scheduler
  template:
    metadata:
      labels:
        name: harmony-work-scheduler
    spec:
      containers:
        - name: harmony-work-scheduler
          imagePullPolicy: IfNotPresent
          image: $WORK_ITEM_SCHEDULER_IMAGE
          resources:
            limits:
              memory: $WORK_ITEM_SCHEDULER_LIMITS_MEMORY
              cpu: $WORK_ITEM_SCHEDULER_LIMITS_CPU
            requests:
              memory: $WORK_ITEM_SCHEDULER_REQUESTS_MEMORY
              cpu: $WORK_ITEM_SCHEDULER_REQUESTS_CPU
          envFrom:
          - configMapRef:
              name: harmony-env
          - secretRef:
              name: harmony-secrets
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: harmony-work-scheduler
spec:
  ports:
    - name: frontend
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    name: harmony-work-scheduler
  type: ClusterIP